device: "cuda:0"   # or "cpu" if you don't have a GPU

data:
  x_path: "C:/Users/user/Desktop/tr/x_train.npy"
  y_path: "C:/Users/user/Desktop/tr/y_train.npy"
  subset_size: 500
  train_split: 0.8

training:
  batch_size: 4
  epochs: 100
  lr: 0.001
  weight_decay: 0.0001
  early_stop: True

physics:
  noise_sigma: 0.00001   # Add this for your GaussianNoise
