# SUNet.yaml - Configuration for SUNet model (Inference Only)
model:
  name: "SUNet"
  type: "pre-trained"
  input_size: [1, 1, 32, 32]
  output_size: [1, 1, 128, 128]
  checkpoint_path: "../SUNet-main/checkpoints/SUNet_model_bestSSIM_ep-400_bs-16_ps-1.pth"
  sunet_path: "../SUNet-main/"

data:
  test_data_path: "C:/Users/user/Desktop/tr/TEST_candels_lsst_sim.pkl"
  default_index: 0
  sampling_factor: 16

processing:
  interpolation_method: "INTER_AREA"
  upsampling_method: "INTER_CUBIC"
  device: 'gpu'

output:
  default_output_dir: "../results/SUNet_images_results"
  save_individual_images: true
  save_comparison_plot: true
  save_numpy_arrays: true
  save_metrics: true

visualization:
  colormap: "RdBu_r"
  dpi: 300
  figsize: [18, 6]

logging:
  print_flattened_arrays: true
  array_precision: 6
  array_threshold: 20
  array_linewidth: 100